
export const FETCH_PARAMS_FROM_URL = 'FETCH_PARAMS_FROM_URL';
export const FETCH_EFORM_TEMPLATE_FROM_SERVER = 'FETCH_EFORM_TEMPLATE_FROM_SERVER';
export const FETCH_USER_ROLE_FROM_SERVER = 'FETCH_USER_ROLE_FROM_SERVER';
export const FETCH_APPOINTMENT_FROM_SERVER = 'FETCH_APPOINTMENT_FROM_SERVER';
export const FETCH_DOCTOR_INFO_FROM_SERVER = 'FETCH_DOCTOR_INFO_FROM_SERVER';

export const FETCH_APPOINTMENT_INFO_FROM_SERVER = 'FETCH_APPOINTMENT_INFO_FROM_SERVER';

export const FETCH_PATIENT_FROM_SERVER = 'FETCH_PATIENT_FROM_SERVER';
export const FETCH_EFORM_DATA_FROM_SERVER = 'FETCH_EFORM_DATA_FROM_SERVER';
export const FETCH_EFORM_ISSHOW_UID_FROM_SERVER = 'FETCH_EFORM_ISSHOW_UID_FROM_SERVER';

export const FILL_IN_DATA = 'FILL_IN_DATA';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_RADIO = 'UPDATE_RADIO';
